[build]
  command = "cd client && npx vite build && cd ../server && npm run build"
  functions = "server/functions"
  publish = "client/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200